blank_issues_enabled: false
contact_links:
  - name: ğŸ“„ å®˜æ–¹æ–‡æ¡£
    url: https://bili23.scott-slan.cn/
    about: åœ¨åˆ›å»º Issue ä¹‹å‰ï¼Œè¯·ä»”ç»†æŸ¥é˜… Bili23 Downloader ä½¿ç”¨æ‰‹å†Œä»¥ç¡®ä¿æ­£ç¡®ä½¿ç”¨ã€‚
